/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pk_electroniccity;

import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import pk_electroniccity.Home;

/**
 *
 * @author lenovo
 */
public class T_KerjaSamaTim extends javax.swing.JFrame {
    private Home home;
    /**
     * Creates new form T_KerjaSamaTim
     */
    public T_KerjaSamaTim(Home home) {
        initComponents();
        loadkomunikasi();
        loadantardivisi();
        loaddalamdivisi();
        this.home = home;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

public void loadkomunikasi(){
    DefaultComboBoxModel <String> model = new DefaultComboBoxModel<>();
    model.addElement("Sangat Baik");
    model.addElement("Baik");
    model.addElement("Cukup");
    model.addElement("Buruk");
    model.addElement("Sangat Buruk");
    comkomunikasi.setModel(model);
}

public void loadantardivisi(){
    DefaultComboBoxModel <String> model = new DefaultComboBoxModel<>();
    model.addElement("Sangat Baik");
    model.addElement("Baik");
    model.addElement("Cukup");
    model.addElement("Buruk");
    model.addElement("Sangat Buruk");
    comantardivisi.setModel(model);
}

public void loaddalamdivisi(){
    DefaultComboBoxModel <String> model = new DefaultComboBoxModel<>();
    model.addElement("Sangat Baik");
    model.addElement("Baik");
    model.addElement("Cukup");
    model.addElement("Buruk");
    model.addElement("Sangat Buruk");
    comdalamdivisi.setModel(model);   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comkomunikasi = new javax.swing.JComboBox<>();
        comdalamdivisi = new javax.swing.JComboBox<>();
        comantardivisi = new javax.swing.JComboBox<>();
        bt_simpankomunikasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("KOMUNIKASI");

        jLabel2.setText("KERJASAMA DALAM DIVISI");

        jLabel3.setText("KERJASAMA ANTAR DIVISI");

        bt_simpankomunikasi.setText("SIMPAN");
        bt_simpankomunikasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 114, 198)));
        bt_simpankomunikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpankomunikasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(comantardivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comkomunikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comdalamdivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(bt_simpankomunikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comkomunikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comdalamdivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comantardivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_simpankomunikasi)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_simpankomunikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpankomunikasiActionPerformed
        String komunikasi = (String) comkomunikasi.getSelectedItem();
        String dalamdivisi = (String) comdalamdivisi.getSelectedItem();
        String antardivisi = (String) comantardivisi.getSelectedItem();
        
        int nilaikomunikasi = 0 ;
        int nilaidalamdivisi = 0;
        int nilaiantardivisi = 0;
                
        switch (komunikasi) {
            case "Sangat Baik":
                nilaikomunikasi = 5;
                break;
            case "Baik":
                nilaikomunikasi = 4;
                break;
            case "Cukup":
                nilaikomunikasi = 3;
                break;
            case "Buruk":
                nilaikomunikasi = 2;
                break;
            case "Sangat Buruk":
                nilaikomunikasi = 1;
                break;
            default:
                nilaikomunikasi = 0;
                break;
        }
        
        switch (dalamdivisi) {
            case "Sangat Baik":
                nilaidalamdivisi = 5;
                break;
            case "Baik":
                nilaidalamdivisi = 4;
                break;
            case "Cukup":
                nilaidalamdivisi = 3;
                break;
            case "Buruk":
                nilaidalamdivisi = 2;
                break;
            case "Sangat Buruk":
                nilaidalamdivisi = 1;
                break;
            default:
                nilaidalamdivisi = 0;
                break;
        }        
        
        switch (antardivisi) {
            case "Sangat Baik":
                nilaiantardivisi = 5;
                break;
            case "Baik":
                nilaiantardivisi = 4;
                break;
            case "Cukup":
                nilaiantardivisi = 3;
                break;
            case "Buruk":
                nilaiantardivisi = 2;
                break;
            case "Sangat Buruk":
                nilaiantardivisi = 1;
                break;
            default:
                nilaiantardivisi = 0;
                break;
        }
        
        double hasilkerjasama = (nilaikomunikasi * 0.4) + (nilaidalamdivisi * 0.3)+(nilaiantardivisi * 0.3);  
        DecimalFormat df = new DecimalFormat("0");
        String formatkerjasama = df.format(hasilkerjasama);
        
        if (home != null) {
            home.setK3(formatkerjasama);
        }
        this.dispose();
    }//GEN-LAST:event_bt_simpankomunikasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_KerjaSamaTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_KerjaSamaTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_KerjaSamaTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_KerjaSamaTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Home home = new Home();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_KerjaSamaTim(home).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_simpankomunikasi;
    private javax.swing.JComboBox<String> comantardivisi;
    private javax.swing.JComboBox<String> comdalamdivisi;
    private javax.swing.JComboBox<String> comkomunikasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
