/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pk_electroniccity;

import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import pk_electroniccity.Home;

/**
 *
 * @author lenovo
 */
public class T_Kinerja extends javax.swing.JFrame {
    private Home home;
    /**
     * Creates new form T_KemampuanTeknis
     */
    public T_Kinerja(Home home) {
        initComponents();
        this.home = home;
        loadnilaisop();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void loadnilaisop(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Sangat Baik");
        model.addElement("Baik");
        model.addElement("Cukup");
        model.addElement("Buruk");
        model.addElement("Sangat Buruk");
        combosop.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputkesalahan = new javax.swing.JTextField();
        combosop = new javax.swing.JComboBox<>();
        simpankinerja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("KESALAHAN KERJA");

        jLabel2.setText("KEPATUHAN SOP");

        inputkesalahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputkesalahanActionPerformed(evt);
            }
        });

        combosop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosopActionPerformed(evt);
            }
        });

        simpankinerja.setText("SIMPAN");
        simpankinerja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 114, 198)));
        simpankinerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpankinerjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combosop, 0, 112, Short.MAX_VALUE)
                            .addComponent(inputkesalahan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(simpankinerja, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputkesalahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combosop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(simpankinerja)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputkesalahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputkesalahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputkesalahanActionPerformed

    private void simpankinerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpankinerjaActionPerformed
        String kesalahan = inputkesalahan.getText();
        String sop = (String) combosop.getSelectedItem();
        
        double totalkesalahan = Double.parseDouble(kesalahan);
        
        int nilaikesalahan = 0;
        if (totalkesalahan == 0) {
            nilaikesalahan = 5;
        } else if (totalkesalahan >= 1 && totalkesalahan <= 2) {
            nilaikesalahan = 4;
        } else if (totalkesalahan > 2 && totalkesalahan <= 5) {
            nilaikesalahan = 3;
        } else if (totalkesalahan > 5 && totalkesalahan <= 8) {
            nilaikesalahan = 2;
        } else if (totalkesalahan > 8) {
            nilaikesalahan = 1;
        }       
        
        int nilaisop = 0;
        
        switch (sop) {
            case "Sangat Baik":
             nilaisop = 5;   
                break;
            case "Baik":
             nilaisop = 4;   
                break;
            case "Cukup":
             nilaisop = 3;   
                break;
            case "Buruk":
             nilaisop = 2;   
                break;
            case "Sangat Buruk":
             nilaisop = 1;   
                break;
            default:
              nilaisop = 0;
                break;
        }
        
        double hasilkinerja = (nilaikesalahan + nilaisop) / 2;
        DecimalFormat df = new DecimalFormat("0");
        String formatkinerja = df.format(hasilkinerja);
        
        if (home != null) {
            home.setK2(formatkinerja);
        }
        this.dispose();
    }//GEN-LAST:event_simpankinerjaActionPerformed

    private void combosopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosopActionPerformed

    }//GEN-LAST:event_combosopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_Kinerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_Kinerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_Kinerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_Kinerja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        Home home = new Home();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_Kinerja(home).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combosop;
    private javax.swing.JTextField inputkesalahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton simpankinerja;
    // End of variables declaration//GEN-END:variables
}
