/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pk_electroniccity;

import javax.swing.JFrame;

/**
 *
 * @author lenovo
 */
public class T_PencapaianPenjualan extends javax.swing.JFrame {
private Home home;
    /**
     * Creates new form T_PencapaianPenjualan
     */
    public T_PencapaianPenjualan(Home home) {
        initComponents();
        this.home = home;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputbulan1 = new javax.swing.JTextField();
        inputbulan2 = new javax.swing.JTextField();
        inputbulan3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        targetbulan1 = new javax.swing.JTextField();
        targetbulan2 = new javax.swing.JTextField();
        targetbulan3 = new javax.swing.JTextField();
        bt_simpanpenjualan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("PENCAPAIAN BULAN 1");

        jLabel2.setText("PENCAPAIAN BULAN 2");

        jLabel3.setText("PENCAPAIAN BULAN 3");

        inputbulan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbulan1ActionPerformed(evt);
            }
        });

        inputbulan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbulan2ActionPerformed(evt);
            }
        });

        inputbulan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputbulan3ActionPerformed(evt);
            }
        });

        jLabel4.setText("DARI");

        jLabel5.setText("DARI");

        jLabel6.setText("DARI");

        targetbulan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetbulan1ActionPerformed(evt);
            }
        });

        targetbulan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetbulan2ActionPerformed(evt);
            }
        });

        targetbulan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetbulan3ActionPerformed(evt);
            }
        });

        bt_simpanpenjualan.setText("SIMPAN");
        bt_simpanpenjualan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 114, 198)));
        bt_simpanpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanpenjualanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_simpanpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputbulan1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputbulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(targetbulan1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(targetbulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(targetbulan3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(inputbulan3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(targetbulan1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(targetbulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(targetbulan3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputbulan1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputbulan2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputbulan3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(bt_simpanpenjualan)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputbulan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbulan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputbulan1ActionPerformed

    private void inputbulan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbulan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputbulan2ActionPerformed

    private void inputbulan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputbulan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputbulan3ActionPerformed

    private void targetbulan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetbulan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetbulan1ActionPerformed

    private void targetbulan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetbulan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetbulan2ActionPerformed

    private void targetbulan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetbulan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetbulan3ActionPerformed

    private void bt_simpanpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanpenjualanActionPerformed
        String bulan1 = inputbulan1.getText();
        String bulan2 = inputbulan2.getText();
        String bulan3 = inputbulan3.getText();
        String tbulan1 = targetbulan1.getText();
        String tbulan2 = targetbulan2.getText();
        String tbulan3 = targetbulan3.getText();
        
        double databulan1 = Double.parseDouble(bulan1);
        double databulan2 = Double.parseDouble(bulan2);
        double databulan3 = Double.parseDouble(bulan3);
        double datatbulan1 = Double.parseDouble(tbulan1);
        double datatbulan2 = Double.parseDouble(tbulan2);
        double datatbulan3 = Double.parseDouble(tbulan3);
        
        double hitbulan1 = (databulan1 / datatbulan1) * 100;
        double hitbulan2 = (databulan2 / datatbulan2) * 100;
        double hitbulan3 = (databulan3 / datatbulan3) * 100;
        
        double hasilpenjualan = (hitbulan1 + hitbulan2 + hitbulan3) / 3 ;
        
        String nilaipenjualan = null;
        if (hasilpenjualan >95) {
            nilaipenjualan = "5";
        }else if (hasilpenjualan >=80 && hasilpenjualan <95) {
            nilaipenjualan = "4";
        }else if (hasilpenjualan >=60 && hasilpenjualan <80) {
            nilaipenjualan = "3";
        }else if (hasilpenjualan >=40 && hasilpenjualan <60) {
            nilaipenjualan = "2";
        }else if (hasilpenjualan <40){
            nilaipenjualan = "1";
        }

        if (home != null) {
        home.setK5(nilaipenjualan);
        }
        this.dispose();
        
    }//GEN-LAST:event_bt_simpanpenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_PencapaianPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_PencapaianPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_PencapaianPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_PencapaianPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Home home = new Home();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_PencapaianPenjualan(home).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_simpanpenjualan;
    private javax.swing.JTextField inputbulan1;
    private javax.swing.JTextField inputbulan2;
    private javax.swing.JTextField inputbulan3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField targetbulan1;
    private javax.swing.JTextField targetbulan2;
    private javax.swing.JTextField targetbulan3;
    // End of variables declaration//GEN-END:variables
}
